version: '3.4'

services:
  people-registry:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 4000:80
  nginx: 
    image: nginx
    volumes: 
      - './dist:/usr/share/nginx/html'
    ports:
      - 3000:80
